# Generated by Django 4.2.7 on 2024-09-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=155)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="news/")),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField()),
            ],
            options={
                "verbose_name": "Новость",
                "verbose_name_plural": "Новости",
            },
        ),
    ]
