# Generated by Django 4.2.7 on 2024-09-23 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="CategoryNews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Спорт", "Спорт"),
                            ("Музыка", "Музыка"),
                            ("Star", "Star"),
                        ],
                        max_length=155,
                        verbose_name="Тип Категорий",
                    ),
                ),
                (
                    "title",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="news.news",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Категерий",
            },
        ),
    ]
